#!/usr/bin/env python3
"""Post-process multichannel beep edges from batch beep summaries.

The script reads a `beep_summary.json` generated by a batch detector plus a
previous edge CSV, then applies the multichannel boundary policy:

- full/continuous mic-like channels determine event boundaries;
- delayed/sparse/burst reference channels confirm an event but do not drag edges;
- device profiles may pin known mic/reference/ignored channels for 4/6/8-channel
  recordings.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path, PureWindowsPath
from typing import Any


CN = {
    "audio": "\u97f3\u9891\u540d\u79f0",
    "head_start": "\u5f00\u5934bee\u5f00\u59cb\u4f4d\u7f6e",
    "head_end": "\u5f00\u5934bee\u7ed3\u675f\u4f4d\u7f6e",
    "tail_start": "\u7ed3\u5c3ebee\u5f00\u59cb\u4f4d\u7f6e",
    "tail_end": "\u7ed3\u5c3ebee\u7ed3\u675f\u4f4d\u7f6e",
    "head_fix": "\u5f00\u5934\u5f00\u59cb\u4fee\u6b63ms",
    "tail_fix": "\u7ed3\u5c3e\u5f00\u59cb\u4fee\u6b63ms",
    "head_residual": "\u5f00\u5934\u4e0emic\u8d77\u70b9\u5deems",
    "tail_residual": "\u7ed3\u5c3e\u4e0emic\u8d77\u70b9\u5deems",
    "head_note": "\u5f00\u5934\u8bf4\u660e",
    "tail_note": "\u7ed3\u5c3e\u8bf4\u660e",
    "mic_channels": "mic\u901a\u9053",
    "reference_channels": "\u53c2\u8003\u901a\u9053",
}

NOTE = {
    "no_primary": "\u65e0\u4e3b\u8fb9\u754c\u5019\u9009\uff0c\u4fdd\u6301\u65e7\u503c",
    "head_fix": "\u5f00\u5934\u4e3b\u8fb9\u754c\u8d77\u70b9\u66f4\u65e9\uff0c\u4fee\u6b63\u5230\u4e3b\u8fb9\u754c",
    "head_later": "\u5f00\u5934\u4e3b\u8fb9\u754c\u66f4\u665a\uff0c\u4fdd\u62a4\u65e7\u503c\u907f\u514d\u8fc7\u5ea6\u540e\u79fb",
    "head_keep": "\u5f00\u5934\u5dee\u5f02\u672a\u8d85\u8fc7\u9608\u503c\uff0c\u4fdd\u6301\u65e7\u503c",
    "tail_fix": "\u7ed3\u5c3e\u4e3b\u8fb9\u754c\u8d77\u70b9\u66f4\u65e9\uff0c\u4fee\u6b63\u5230\u4e3b\u8fb9\u754c",
    "tail_keep": "\u7ed3\u5c3e\u5dee\u5f02\u672a\u8d85\u8fc7\u9608\u503c\uff0c\u4fdd\u6301\u65e7\u503c",
}


def time_text(seconds: float) -> str:
    total_ms = int(round(seconds * 1000))
    minutes = total_ms // 60000
    sec = (total_ms % 60000) // 1000
    ms = total_ms % 1000
    return f"{minutes}\u5206{sec:02d}\u79d2{ms:03d}\u6beb\u79d2"


def overlap(left_start: float, left_end: float, right_start: float, right_end: float) -> float:
    return max(0.0, min(left_end, right_end) - max(left_start, right_start))


def parse_channel_set(text: str | None) -> set[int]:
    if not text:
        return set()
    result: set[int] = set()
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            left, right = part.split("-", 1)
            result.update(range(int(left), int(right) + 1))
        else:
            result.add(int(part))
    return result


def split_suffix(path: Path) -> tuple[str, int] | None:
    match = re.match(r"^(.*)_([0-9]+)$", path.stem)
    if not match:
        return None
    return match.group(1), int(match.group(2))


def logical_path_for_entry(entry: dict[str, Any]) -> Path:
    path = Path(entry["path"])
    if entry.get("split_channel_index") is None:
        return path
    suffix = split_suffix(path)
    if not suffix:
        return path
    prefix, _ = suffix
    return path.with_name(prefix + path.suffix)


def marker_channel(entry: dict[str, Any], channel: dict[str, Any]) -> int:
    split = entry.get("split_channel_index")
    if split is not None:
        return int(split)
    return int(channel.get("physical_channel") or 0)


def top_escape(path: Path, root: Path) -> str:
    try:
        top = path.relative_to(root).parts[0]
    except ValueError:
        top = path.parts[0]
    return top.encode("unicode_escape").decode("ascii")


def normalize_audio_key(text: str) -> str:
    """Normalize CSV audio keys so duplicate basenames stay distinguishable."""
    if not text:
        return ""
    return str(PureWindowsPath(text.replace("/", "\\")))


def read_groups(summary_json: Path, root: Path, target_top_escape: str) -> dict[str, dict[str, Any]]:
    data = json.loads(summary_json.read_text(encoding="utf-8"))
    groups: dict[str, dict[str, Any]] = {}
    for entry in data:
        logical = logical_path_for_entry(entry)
        if top_escape(logical, root) != target_top_escape:
            continue
        key = str(logical)
        group = groups.setdefault(
            key,
            {
                "logical_path": logical,
                "duration_sec": float(entry.get("duration_sec") or 0.0),
                "channels": {},
            },
        )
        group["duration_sec"] = max(group["duration_sec"], float(entry.get("duration_sec") or 0.0))
        for channel in entry.get("channels", []) or []:
            ch_index = marker_channel(entry, channel)
            ch = group["channels"].setdefault(
                ch_index,
                {
                    "index": ch_index,
                    "is_empty": False,
                    "peak": 0,
                    "markers": [],
                },
            )
            ch["is_empty"] = ch["is_empty"] or bool(channel.get("is_empty"))
            ch["peak"] = max(int(ch.get("peak") or 0), int(channel.get("peak") or 0))
            ch["markers"].extend(channel.get("markers", []) or [])
    return groups


def read_previous_edges(previous_csv: Path, target_top_escape: str) -> dict[str, dict[str, dict[str, str]]]:
    rows = list(csv.DictReader(previous_csv.open("r", encoding="utf-8-sig")))
    edges: dict[str, dict[str, dict[str, str]]] = {}
    for row in rows:
        if "top" in row:
            row_top_escape = row["top"].encode("unicode_escape").decode("ascii")
            if row_top_escape != target_top_escape:
                continue
        elif "audio" in row:
            first_part = Path(row["audio"]).parts[0]
            if first_part.encode("unicode_escape").decode("ascii") != target_top_escape:
                continue
        else:
            continue
        audio_key = normalize_audio_key(row.get("audio") or row.get(CN["audio"]) or "")
        side = row.get("pos")
        if not audio_key or side not in {"head", "tail"}:
            continue
        edges.setdefault(audio_key, {})[side] = row
    return edges


def is_full_boundary_marker(marker: dict[str, Any]) -> bool:
    if marker.get("detection_type") == "continuous_pair":
        return True
    return False


def collect_candidates(
    group: dict[str, Any],
    old_start: float,
    old_end: float,
    profile: str,
    mic_channels: set[int],
    reference_channels: set[int],
    ignore_channels: set[int],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    primary: list[dict[str, Any]] = []
    reference: list[dict[str, Any]] = []
    for ch_index, channel in sorted(group["channels"].items()):
        if ch_index in ignore_channels or channel.get("is_empty") or int(channel.get("peak") or 0) < 100:
            continue
        for marker in channel.get("markers", []) or []:
            start = float(marker["start"])
            end = float(marker["end"])
            if (
                overlap(start, end, old_start - 1.0, old_end + 1.0) <= 0.0
                and abs(start - old_start) >= 1.5
                and abs(end - old_end) >= 1.5
            ):
                continue
            item = {
                "channel": ch_index,
                "start": start,
                "end": end,
                "ratio": float(marker.get("mean_tone_ratio_1khz") or 0.0),
                "type": marker.get("detection_type") or "",
                "confidence": marker.get("confidence") or "",
            }
            if profile == "known":
                if ch_index in mic_channels:
                    primary.append(item)
                elif ch_index in reference_channels:
                    reference.append(item)
                continue
            if is_full_boundary_marker(marker):
                primary.append(item)
            else:
                reference.append(item)
    return primary, reference


def filter_primary_candidates(primary: list[dict[str, Any]], args: argparse.Namespace) -> list[dict[str, Any]]:
    filtered = list(primary)
    if not args.allow_burst_primary:
        filtered = [item for item in filtered if item.get("type") == "continuous_pair"]
    if args.min_primary_ratio > 0:
        filtered = [item for item in filtered if float(item.get("ratio") or 0.0) >= args.min_primary_ratio]
    if args.min_primary_support > 1:
        channels = {int(item["channel"]) for item in filtered}
        if len(channels) < args.min_primary_support:
            return []
    return filtered


def consensus_start(primary: list[dict[str, Any]]) -> float | None:
    starts = sorted(float(item["start"]) for item in primary)
    if not starts:
        return None
    if len(starts) == 1:
        return starts[0]
    # Ignore a single isolated early outlier unless another channel agrees within 100 ms.
    if starts[1] - starts[0] <= 0.100:
        return starts[0]
    return starts[1]


def consensus_end(primary: list[dict[str, Any]]) -> float | None:
    ends = sorted((float(item["end"]) for item in primary), reverse=True)
    if not ends:
        return None
    if len(ends) == 1:
        return ends[0]
    if ends[0] - ends[1] <= 0.100:
        return ends[0]
    return ends[1]


def choose_edge(
    old_start: float,
    old_end: float,
    primary: list[dict[str, Any]],
    side: str,
    head_start_fix_ms: float,
    tail_start_fix_ms: float,
    end_fix_ms: float,
) -> tuple[float, float, str, int | None, int | None]:
    primary_start = consensus_start(primary)
    primary_end = consensus_end(primary)
    new_start = old_start
    new_end = old_end
    note = NOTE["no_primary"]
    start_residual = None
    end_residual = None
    if primary_start is not None:
        start_delta_ms = (primary_start - old_start) * 1000.0
        threshold = head_start_fix_ms if side == "head" else tail_start_fix_ms
        if start_delta_ms < -threshold:
            new_start = primary_start
            note = NOTE["head_fix"] if side == "head" else NOTE["tail_fix"]
        elif side == "head" and start_delta_ms > head_start_fix_ms:
            note = NOTE["head_later"]
        else:
            note = NOTE["head_keep"] if side == "head" else NOTE["tail_keep"]
        start_residual = int(round((new_start - primary_start) * 1000.0))
    if primary_end is not None:
        end_delta_ms = (primary_end - old_end) * 1000.0
        if abs(end_delta_ms) > end_fix_ms:
            new_end = primary_end
            note = note + "\uff1b\u7ed3\u675f\u70b9\u4fee\u6b63\u5230\u4e3b\u8fb9\u754c"
        end_residual = int(round((new_end - primary_end) * 1000.0))
    return new_start, new_end, note, start_residual, end_residual


def process(args: argparse.Namespace) -> list[dict[str, Any]]:
    root = args.root.resolve()
    target_top_escape = args.target_top_escape
    groups = read_groups(args.summary_json.resolve(), root, target_top_escape)
    previous = read_previous_edges(args.previous_csv.resolve(), target_top_escape)
    mic_channels = parse_channel_set(args.mic_channels)
    reference_channels = parse_channel_set(args.reference_channels)
    ignore_channels = parse_channel_set(args.ignore_channels)
    rows: list[dict[str, Any]] = []
    for key, group in sorted(groups.items(), key=lambda item: str(item[1]["logical_path"])):
        audio_key = normalize_audio_key(str(group["logical_path"].relative_to(root)))
        if audio_key not in previous:
            continue
        item: dict[str, Any] = {
            "audio": audio_key,
        }
        for side in ("head", "tail"):
            edge = previous[audio_key].get(side)
            if not edge:
                continue
            old_start = float(edge["start_sec"])
            old_end = float(edge["end_sec"])
            primary, reference = collect_candidates(
                group,
                old_start,
                old_end,
                "known" if args.profile == "known" else "auto",
                mic_channels,
                reference_channels,
                ignore_channels,
            )
            primary = filter_primary_candidates(primary, args)
            if args.skip_unreliable_primary and not primary:
                continue
            new_start, new_end, note, start_residual, end_residual = choose_edge(
                old_start,
                old_end,
                primary,
                side,
                args.head_start_fix_ms,
                args.tail_start_fix_ms,
                args.end_fix_ms,
            )
            item[f"{side}_start_sec"] = new_start
            item[f"{side}_end_sec"] = new_end
            item[f"{side}_start_text"] = time_text(new_start)
            item[f"{side}_end_text"] = time_text(new_end)
            item[f"{side}_start_fix_ms"] = int(round((new_start - old_start) * 1000.0))
            item[f"{side}_end_fix_ms"] = int(round((new_end - old_end) * 1000.0))
            item[f"{side}_start_residual_ms"] = "" if start_residual is None else start_residual
            item[f"{side}_end_residual_ms"] = "" if end_residual is None else end_residual
            item[f"{side}_primary_channels"] = ",".join(str(i) for i in sorted({p["channel"] for p in primary}))
            item[f"{side}_reference_channels"] = ",".join(str(i) for i in sorted({r["channel"] for r in reference}))
            item[f"{side}_note"] = note
        if args.skip_unreliable_primary and "head_start_sec" not in item and "tail_start_sec" not in item:
            continue
        rows.append(item)
    return rows


def write_outputs(rows: list[dict[str, Any]], out_csv: Path, simple_csv: Path | None) -> None:
    detail_fields = [
        "audio",
        "head_start_text",
        "head_end_text",
        "head_start_fix_ms",
        "head_end_fix_ms",
        "head_start_residual_ms",
        "head_end_residual_ms",
        "head_primary_channels",
        "head_reference_channels",
        "head_note",
        "tail_start_text",
        "tail_end_text",
        "tail_start_fix_ms",
        "tail_end_fix_ms",
        "tail_start_residual_ms",
        "tail_end_residual_ms",
        "tail_primary_channels",
        "tail_reference_channels",
        "tail_note",
    ]
    detail_headers = [
        CN["audio"],
        CN["head_start"],
        CN["head_end"],
        CN["head_fix"],
        "\u5f00\u5934\u7ed3\u675f\u4fee\u6b63ms",
        CN["head_residual"],
        "\u5f00\u5934\u4e0emic\u7ec8\u70b9\u5deems",
        "\u5f00\u5934" + CN["mic_channels"],
        "\u5f00\u5934" + CN["reference_channels"],
        CN["head_note"],
        CN["tail_start"],
        CN["tail_end"],
        CN["tail_fix"],
        "\u7ed3\u5c3e\u7ed3\u675f\u4fee\u6b63ms",
        CN["tail_residual"],
        "\u7ed3\u5c3e\u4e0emic\u7ec8\u70b9\u5deems",
        "\u7ed3\u5c3e" + CN["mic_channels"],
        "\u7ed3\u5c3e" + CN["reference_channels"],
        CN["tail_note"],
    ]
    with out_csv.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(detail_headers)
        for row in rows:
            writer.writerow([row.get(field, "") for field in detail_fields])
    if simple_csv:
        with simple_csv.open("w", encoding="utf-8-sig", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow([CN["audio"], CN["head_start"], CN["head_end"], CN["tail_start"], CN["tail_end"]])
            for row in rows:
                writer.writerow(
                    [
                        row.get("audio", ""),
                        row.get("head_start_text", ""),
                        row.get("head_end_text", ""),
                        row.get("tail_start_text", ""),
                        row.get("tail_end_text", ""),
                    ]
                )


def main() -> int:
    parser = argparse.ArgumentParser(description="Post-process multichannel beep edges from batch summaries.")
    parser.add_argument("--root", type=Path, required=True, help="Dataset root used by summary paths")
    parser.add_argument("--summary-json", type=Path, required=True, help="Batch beep_summary.json")
    parser.add_argument("--previous-csv", type=Path, required=True, help="Previous edge CSV with top/audio/pos/start_sec/end_sec")
    parser.add_argument("--target-top-escape", required=True, help="Top directory name encoded by Python unicode_escape")
    parser.add_argument("--out-csv", type=Path, required=True, help="Detailed output CSV")
    parser.add_argument("--simple-csv", type=Path, help="Optional concise output CSV")
    parser.add_argument("--profile", choices=["auto", "known"], default="auto")
    parser.add_argument("--mic-channels", default="", help="Known mic channels, e.g. 0,1")
    parser.add_argument("--reference-channels", default="", help="Known reference channels, e.g. 5,6")
    parser.add_argument("--ignore-channels", default="", help="Channels to ignore, e.g. 2,3,4,7")
    parser.add_argument("--head-start-fix-ms", type=float, default=50.0)
    parser.add_argument("--tail-start-fix-ms", type=float, default=100.0)
    parser.add_argument("--end-fix-ms", type=float, default=100.0)
    parser.add_argument(
        "--reject-burst-primary",
        dest="allow_burst_primary",
        action="store_false",
        help="Do not use burst_pair markers as primary boundary evidence",
    )
    parser.set_defaults(allow_burst_primary=True)
    parser.add_argument("--min-primary-ratio", type=float, default=0.0, help="Minimum tone ratio for primary markers")
    parser.add_argument("--min-primary-support", type=int, default=1, help="Minimum distinct primary channels required")
    parser.add_argument(
        "--skip-unreliable-primary",
        action="store_true",
        help="Skip a side/audio when no primary candidate survives evidence filters",
    )
    args = parser.parse_args()

    rows = process(args)
    write_outputs(rows, args.out_csv, args.simple_csv)
    print(
        json.dumps(
            {
                "files": len(rows),
                "out_csv": str(args.out_csv),
                "simple_csv": str(args.simple_csv) if args.simple_csv else None,
                "head_start_changed": sum(1 for row in rows if row.get("head_start_fix_ms", 0) != 0),
                "tail_start_changed": sum(1 for row in rows if row.get("tail_start_fix_ms", 0) != 0),
                "head_end_changed": sum(1 for row in rows if row.get("head_end_fix_ms", 0) != 0),
                "tail_end_changed": sum(1 for row in rows if row.get("tail_end_fix_ms", 0) != 0),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
